# Generated by Django 3.1.7 on 2021-03-12 01:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('payload', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True)),
                ('command', models.CharField(max_length=100, verbose_name='command')),
                (
                    'createdAt', models.DateTimeField(
                        auto_now_add=True, verbose_name='Created At',
                    ),
                ),
                (
                    'bot', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bots.bot',
                    ),
                ),
                (
                    'response_profile', models.ForeignKey(
                        default=2, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile',
                    ),
                ),
            ],
        ),
    ]
