# Generated by Django 3.1.7 on 2021-03-12 01:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('groups', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('chat_id', models.CharField(max_length=100, verbose_name='chat_id')),
                (
                    'first_name', models.CharField(
                        default='', max_length=100, null=True,
                    ),
                ),
                (
                    'last_name', models.CharField(
                        default='', max_length=100, null=True,
                    ),
                ),
                ('username', models.CharField(default='', max_length=100, null=True)),
                ('response_enabled', models.BooleanField(default=False)),
                (
                    'createdAt', models.DateTimeField(
                        auto_now_add=True, verbose_name='Created At',
                    ),
                ),
                (
                    'bot', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bots.bot',
                    ),
                ),
                ('groups', models.ManyToManyField(to='groups.Group')),
                (
                    'profile', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='profiles.profile',
                    ),
                ),
            ],
        ),
    ]
